---
name: CI Jobs

on: push

jobs:
  linter:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip3 install --upgrade -r requirements-dev.txt

      - id: black
        run: black --check .

    outputs:
      conclusion: ${{ steps.black.conclusion }}

  pytest:
    runs-on: ubuntu-24.04

    needs: linter
    if: ${{ needs.linter.outputs.conclusion == 'success' }}

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          set -e
          python -m pip install --user --upgrade pip wheel

          pip install -r requirements.txt --upgrade
          pip install -r requirements-dev.txt --upgrade
          pip install -e .

      - name: Test with pytest
        run: pytest
